# Generated by Django 4.2.1 on 2023-05-30 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi5', '0002_raca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('observacao', models.CharField(max_length=300)),
                ('foto', models.ImageField(upload_to='denuncias')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('rua', models.CharField(max_length=90)),
                ('numero_endereco', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoResgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('observacao', models.CharField(max_length=300)),
                ('foto', models.ImageField(upload_to='solicitacoes_resgate')),
            ],
            options={
                'verbose_name': 'SolicitaçãoResgate',
                'verbose_name_plural': 'SolicitaçõesResgate',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to='animais')),
                ('observacao', models.CharField(max_length=200)),
                ('situacao', models.CharField(max_length=100)),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi5.raca')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=200)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi5.animal')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi5.pessoa')),
            ],
            options={
                'verbose_name': 'Adoção',
                'verbose_name_plural': 'Adoções',
            },
        ),
    ]
