# Generated by Django 4.2.1 on 2023-06-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi5', '0004_situacao_alter_animal_situacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adocao',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
